jko:
  rho: 1.2
  h_0: 0.75
  h_max: 5
  d: 2
  sigma_0: 0.02
  num_blocks: 8
jko_train:
  num_points: 10000
  epochs_per_block: 100
  batch_size: 500
  clip_grad: True
  lr: 0.0001
  save_path: train_2
N: 1000
M: 1000
load_JKO: False
