jko:
  rho: 1.2
  h_0: 0.75
  h_max: 5
  d: 2
  sigma_0: 0.02
  num_blocks: 3
jko_train:
  num_points: 10000
  epochs_per_block: 100
  batch_size: 500
  clip_grad: True
  lr: 0.0001
  save_path: train_2
ot_train:
  lr: 3e-4
  clf_lr: 3e-4
  tot_iters: 10
N: 512
M: 512
load_JKO: True
