jko:
  rho: 1.2
  h_0: 0.75
  h_max: 5
  d: 2
  sigma_0: 0.02
  num_blocks: 8
jko_train:
  num_points: 10000
  epochs_per_block: 20
  batch_size: 2048
  clip_grad: True
  lr: 0.01
  save_path: moons_to_checkerboard
ot_train:
  batch_size: 1024
  lr: 5e-5
  clf_lr: 1e-3
  Tot: 2
  E: 50
  E_0: 150
  E_in: 4
  gamma: 0.5
N: 8192
M: 8192
save_path: moons_to_checkerboard_2
load_JKO: True
data:
  P_distribution: moons
  Q_distribution: image
  Q_image_path: img_checkerboard.png
