jko:
  rho: 1.2
  h_0: 0.75
  h_max: 5
  d: 2
  sigma_0: 0.02
  num_blocks: 8
jko_train:
  num_points: 10000
  epochs_per_block: 100
  batch_size: 500
  clip_grad: True
  lr: 0.0001
  save_path: train_2
ot_train:
  batch_size: 8192
  lr: 1e-4
  clf_lr: 1e-4
  Tot: 2
  E: 50
  E_0: 300
  E_in: 4
  gamma: 0.5
N: 8192
M: 8192
load_JKO: True
data:
  P_distribution: moons
  Q_distribution: image
  Q_image_path: img_checkerboard.png
